name:                market-parser
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jproyo/market-parser#readme
github:              jproyo/market-parser
bug-reports:         https://github.com/jproyo/market-parser/issues
license:             BSD3
author:              Juan Pablo Royo Sales
maintainer:          juanpablo.royo@gmail.com
copyright:           2018 Juan Pablo Royo Sales
category:            parser
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - bytestring-conversion
  - binary
  - monad-loops
  - old-time
  - text
  - time
  - unix-time

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings

executables:
  mkt-ps:
    source-dirs:      [src, mktps]
    main:             Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - QuickCheck
